# Generated by Django 3.2.6 on 2021-08-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
    ]
